- name: cfp
  hosts: cfp
  sudo: yes
  vars:
    nginx_listen: 80
    nginx_base_redirect_to_www: false
    nginx_assets_enabled: false
    nginx_server_redirect_to_ssl: false
  roles: 
    - {role: oracle_jdk, oracle_jdk_java_versions: 8, oracle_jdk_java_version_default: 8}
    - {role: redis, redis_requirepass: "<complidatedpasswordhere"}
    - role: elasticsearch
    - role: nginx
    - {role: nginx-site, nginx_base_domain: <yourdomain>, nginx_server_name: <yourdomain>,  nginx_upstream_name: cfp, nginx_upstream_server: '127.0.0.1:9000;', nginx_backend_name: cfp }

  tasks :
    - name: Install unzip
      apt: name=unzip state=present
    # cfp install & launch
    - copy: src=../target/universal/cfp-devoxxfr-1.3-SNAPSHOT.zip dest=/opt/ mode=644 backup=yes
    - unarchive: src=/opt/cfp-devoxxfr-1.3-SNAPSHOT.zip dest=/opt/ copy=no
    - name: create dir for logs
      file: path=/var/log/cfp state=directory mode=777
    - name: Launch CFP
      command: /opt/cfp-devoxxfr-1.3-SNAPSHOT/bin/cfp-devoxxfr >> /var/log/cfp/out.log &